# Generated by Django 5.0.6 on 2024-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuponi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuponi',
            name='qr_code',
            field=models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='QR - код'),
        ),
    ]
