# Generated by Django 5.0.6 on 2024-06-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuponi', '0003_remove_kuponi_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuponi',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
    ]
